### PR TITLE
Add raw functions to use repeated message

### PR DESCRIPTION
**Pull request by juntaki**
buildMessage() is easy to use, but insufficient for repeated message (or maybe other type of nested message) like the following.
https://github.com/juntaki/firestarter/blob/master/proto/config.proto#L49

I had tried to modify buildMessage(), but I thounght adding raw function is simpler and better idea. what do you think of it?

### CODE REVIEW

**Comment by thechriswalker** [comment]
I'm not sure I like the idea of adding API surface area.

To be honest, 1: `buildMessage` is a bit of a hack and 2: perhaps it should all be raw anyway. The `buildMessage` doesn't accept a PB JSON equivalent as it is.

So potentially this would be better for having all functions accept PB message objects directly. I can break the API at this stage, it's still less than `1.0.0`.

**Comment by juntaki** [comment]
Thank you for your reply.
I changed the code. It will accept PB message for default. (just skipping buildMessage).

**Comment by thechriswalker** [comment]
I am happy with this, but will make a coupl of changes to the example code to be ready before it merge it.

**Comment by thechriswalker** [comment]
I rebased your commits, so this code is in despite this not being "merged"

**Pull request closed without merging**
